---
- name: Audit SSH Hardening Settings
  hosts: linux
  become: yes
  gather_facts: no

  vars:
    expected_settings:
      PermitRootLogin: "no"
      PasswordAuthentication: "no"
      PermitEmptyPasswords: "no"

  tasks:

    - name: Read effective sshd configuration
      command: sshd -T
      register: sshd_config_output
      changed_when: false

    - name: Audit SSH settings
      vars:
        lines: "{{ sshd_config_output.stdout_lines }}"
      block:
        - name: Check each expected SSH setting
          set_fact:
            ssh_audit_results: >-
              {{
                expected_settings | dict2items | map('combine', {
                  'actual': (sshd_config_output.stdout | regex_search(item.key ~ '\s+(\S+)', '\\1')),
                  'pass': (sshd_config_output.stdout is search(item.key ~ '\s+' ~ item.value))
                }) | list
              }}

        - name: Show audit result summary
          debug:
            msg: >-
              {% for item in ssh_audit_results %}
              {{ item.key }} = {{ item.actual }} → {{ "✅ PASS" if item.pass else "❌ FAIL (expected: " ~ expected_settings[item.key] ~ ")" }}
              {% endfor %}
